version: "3.8"
services:
  mysql:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reference_java
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

 
